env:
  ProjectName: Atria.Localization
  TagName: Localization

on:
  push:
    tags:
    - "Localization.v*.*.*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Get Version from TagName
      run: echo "VERSION=${GITHUB_REF#refs/tags/${{env.TagName}}.v}" >> $GITHUB_ENV
          
    - name: Print Version
      run: echo ${VERSION}
     
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ${{env.ProjectName}}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      
    #- name: Push
    #  run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
    #  env:
    #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
